booktime/booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    # path("", TemplateView.as_view(template_name="home.html")),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

booktime/main/urls.py
from django.urls import path
from django.views.generic import TemplateView, DetailView
from django.contrib.auth import views as auth_views

from main import views, models, forms

urlpatterns = [
    path(
        "product/<slug:slug>/",
        DetailView.as_view(model=models.Product),
        name='product'
    ),
    path(
        "products/<slug:tag>/",
        views.ProductListView.as_view(),
        name="products",),
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us"),
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        name="home"),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us"),
    path(
        "signup/",
        views.SignmeupView.as_view(),
        name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
    ),
    path(
        "address/",
        views.AddressListView.as_view(),
        name="address_list",
    ),
    path(
        "address/create/",
        views.AddressCreateView.as_view(),
        name="address_create",
    ),
    path(
        "address/<int:pk>/",
        views.AddressUpdateView.as_view(),
        name="address_update",
    ),
    path(
        "address/<int:pk>/delete",
        views.AddressDeleteView.as_view(),
        name="address_delete",
    ),

]

booktime/main/models.py
from django.db import models
from .managers import ActiveManager, ProductTagManager, UserManager

from django.contrib.auth.models import (
    AbstractUser
)
# Create your models here.


class ProductTag(models.Model):
    objects = ProductTagManager()
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug, )


class Product(models.Model):
    objects = ActiveManager()

    tags = models.ManyToManyField(ProductTag,
                                  blank=True)
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6,
                                decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    # name = models.CharField(max_length=32)

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(
        upload_to="product-images"
    )
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )

    def __str__(self):
        return self.product.name


# class ProductTag(models.Model):
#     name = models.CharField(max_length=32)
#     slug = models.SlugField(max_length=48)
#     description = models.TextField(blank=True)
#     active = models.BooleanField(default=True)

#     def __str__(self):
#         return self.name

#     def natural_key(self):
#         return (self.slug, )

class User(AbstractUser):
    username = None
    email = models.EmailField('email address',
                              unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ("np", "Nepal"),
    )
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1",
                                max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )

booktime/main/forms.py
import logging

from django import forms
from django.core.mail import send_mail
# from django.contrib.auth.forms import (
#     UserCreationForm as DjangoUserCreationForm
# )
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UsernameField
from . import models


logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(
        max_length=600,
        widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "raj.shrestha777@gmail.com",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        message = "Welcome{}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "raj.shrestha777@gmail.com",
            [self.cleaned_data["email"]],
            fail_silently=False,
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput
    )

    def __init__(self, request=None, *args,
                 **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email,
                password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination.")
            logger.info(
                "Authentication successful for email=%s", email
            )
        return self.cleaned_data

    def get_user(self):
        return self.user

booktime/main/views.py
import logging

from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)
# from django.views import Template

from main import models, forms

logger = logging.getLogger(__name__)


def home(request):
    return render(request, "home.html", {})


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class ProductListView(ListView):
    template_name = "main/product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != "all":
            self.tag = get_object_or_404(
                models.ProductTag, slug=tag
            )
        if self.tag:
            products = models.Product.objects.active().filter(
                tags=self.tag
            )
        else:
            products = models.Product.objects.active()
        return products.order_by("name")


class SignmeupView(FormView):
    template_name = "signup.html"
    form_class = forms.UserCreateForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info("New signup for email=%s through SignupView",
                    email)
        user = authenticate(email=email,
                            password=raw_password)
        login(self.request, user)
        form.send_mail()
        messages.info(
            self.request, "You signed up successfully."
        )
        return response
        # return super().form_valid(form)


class AddressListView(LoginRequiredMixin, ListView):
    model = models.Address

    def get_queryset(self):
        return self.model.objects.filter(
            user=self.request.user)


class AddressCreateView(LoginRequiredMixin,
                        CreateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin,
                        UpdateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin,
                        DeleteView):
    model = models.Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

booktime/main/templates/main/address_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Delete address</h2>
<form method="POST">
    {%csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

booktime/main/templates/main/address_form.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

booktime/main/templates/main/address_list.html
{% extends "base.html" %}
{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.get_country_display }}<br>
</p>
<p>
    <a href="{% url "address_update" address.id %}">Update address</a>
</p>
<p>
    <a href="{% url "address_delete" address.id %}">Delete address</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url "address_create" %}">Add new address</a>
</p>
{% endblock content %}

booktime/main/templates/main/address_update.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

booktime/main/templates/main/product_detail.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td>
            {% for image in object.productimage_set.all %}
            <img src="{{ image.thumbnail.url }}" alt="cover" />
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:','|default:'No tags available' }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
    97
</table>

{% endblock content %}

booktime/main/templates/main/product_list.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
{% for product in page_obj %}
<p>{{ product.name }}</p>
<p>
    <a href="{% url 'product' product.slug %}">See it here</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %} active {% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}