booktime/booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    # path("", TemplateView.as_view(template_name="home.html")),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

booktime/main/urls.py
from django.urls import path
from django.views.generic import TemplateView, DetailView
from django.contrib.auth import views as auth_views

from main import views, models, forms

urlpatterns = [
    path(
        "product/<slug:slug>/",
        DetailView.as_view(model=models.Product),
        name='product'
    ),
    path(
        "products/<slug:tag>/",
        views.ProductListView.as_view(),
        name="products",),
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us"),
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        name="home"),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us"),
    path(
        "signup/",
        views.SignmeupView.as_view(),
        name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
    ),
    path(
        "address/",
        views.AddressListView.as_view(),
        name="address_list",
    ),
    path(
        "address/create/",
        views.AddressCreateView.as_view(),
        name="address_create",
    ),
    path(
        "address/<int:pk>/",
        views.AddressUpdateView.as_view(),
        name="address_update",
    ),
    path(
        "address/<int:pk>/delete",
        views.AddressDeleteView.as_view(),
        name="address_delete",
    ),

]

booktime/main/models.py
from django.db import models
from .managers import ActiveManager, ProductTagManager, UserManager

from django.contrib.auth.models import (
    AbstractUser
)
# Create your models here.


class ProductTag(models.Model):
    objects = ProductTagManager()
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug, )


class Product(models.Model):
    objects = ActiveManager()

    tags = models.ManyToManyField(ProductTag,
                                  blank=True)
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6,
                                decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    # name = models.CharField(max_length=32)

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(
        upload_to="product-images"
    )
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )

    def __str__(self):
        return self.product.name


# class ProductTag(models.Model):
#     name = models.CharField(max_length=32)
#     slug = models.SlugField(max_length=48)
#     description = models.TextField(blank=True)
#     active = models.BooleanField(default=True)

#     def __str__(self):
#         return self.name

#     def natural_key(self):
#         return (self.slug, )

class User(AbstractUser):
    username = None
    email = models.EmailField('email address',
                              unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ("np", "Nepal"),
    )
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1",
                                max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )

booktime/main/forms.py
import logging

from django import forms
from django.core.mail import send_mail
# from django.contrib.auth.forms import (
#     UserCreationForm as DjangoUserCreationForm
# )
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UsernameField
from . import models


logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(
        max_length=600,
        widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "raj.shrestha777@gmail.com",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        message = "Welcome{}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "raj.shrestha777@gmail.com",
            [self.cleaned_data["email"]],
            fail_silently=False,
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput
    )

    def __init__(self, request=None, *args,
                 **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email,
                password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination.")
            logger.info(
                "Authentication successful for email=%s", email
            )
        return self.cleaned_data

    def get_user(self):
        return self.user

booktime/main/views.py
import logging

from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)
# from django.views import Template

from main import models, forms

logger = logging.getLogger(__name__)


def home(request):
    return render(request, "home.html", {})


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class ProductListView(ListView):
    template_name = "main/product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != "all":
            self.tag = get_object_or_404(
                models.ProductTag, slug=tag
            )
        if self.tag:
            products = models.Product.objects.active().filter(
                tags=self.tag
            )
        else:
            products = models.Product.objects.active()
        return products.order_by("name")


class SignmeupView(FormView):
    template_name = "signup.html"
    form_class = forms.UserCreateForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info("New signup for email=%s through SignupView",
                    email)
        user = authenticate(email=email,
                            password=raw_password)
        login(self.request, user)
        form.send_mail()
        messages.info(
            self.request, "You signed up successfully."
        )
        return response
        # return super().form_valid(form)


class AddressListView(LoginRequiredMixin, ListView):
    model = models.Address

    def get_queryset(self):
        return self.model.objects.filter(
            user=self.request.user)


class AddressCreateView(LoginRequiredMixin,
                        CreateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin,
                        UpdateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country",
    ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin,
                        DeleteView):
    model = models.Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

booktime/main/templates/about_us.html
{% extends "base.html" %}
{% block content %}
  <h2>About us</h2>
  <p>BookTime is a company that sells books online.</p>
{% endblock content %}

booktime/main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  

<head>
        
    <!-- Required meta tags -->
        
    <meta charset="utf-8">
        
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
    <!-- Bootstrap CSS -->
        
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
    <title>BookTime</title>
</head>
  

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Home</a>
                        </li>
                    <li class="nav-item {% if request.path == '/about-us/' %}active{% endif %}">
                    <a class="nav-link" href="/about-us/">About us</a>
                </li>
                    <li class="nav-item {% if request.path == '/contact-us/' %}active{% endif %}">
                    <a class="nav-link" href="/contact-us/">Contact us</a>
                </li>
                    <li class="nav-item {% if request.path == '/products/all/' %}active{% endif %}">
                    <a class="nav-link" href="/products/all/">Products</a>
                </li>
                    <li class="nav-item {% if request.path == '/signup/' %}active{% endif %}">
                    <a class="nav-link" href="/signup/">Signup</a>
                </li>
                </li>
                    <li class="nav-item {% if request.path == '/login/' %}active{% endif %}">
                    <a class="nav-link" href="/login/">Login</a>
                </li>
            </ul>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}     
    <!--     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
    <script src='{% static "js/jquery.min.js" %}'></script>
        <script src='{% static "js/popper.min.js" %}'></script>
        <script src='{% static "js/bootstrap.min.js" %}'></script>
</body>

</html>

booktime/main/templates/contact_form.html
{% extends 'base.html' %}


{% block content %}
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<!-- <form method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn btn-primary">Submit</button>
  </form> -->
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
       {{ form.name.label_tag }}
       <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
     id="id_name" name="name" placeholder="Your name"
     value='{{ form.name.value|default:"" }}''>
       {% if form.name.errors %}
    <div class="invalid-feedback">
       {{ form.name.errors }}
     </div>
       {% endif %}
     </div>
    <div class="form-group">
       {{ form.message.label_tag }}
       <textarea class="form-control {% if form.message.errors %}is-invalid{% endif %}" id="id_message"
     name="message" rows="3">
    {{ form.message.value|default:""}}
       </textarea>
       {% if form.message.errors %}
    <div class="invalid-feedback">
       {{ form.message.errors }}
     </div>
       {% endif %}
     </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

booktime/main/templates/home.html
{% extends "base.html" %}

{% block content %}
  <h2>Home</h2>
  <p>this will be the content of home</p>
{% endblock content %}

booktime/main/templates/login.html
{% extends "base.html" %}
{% block content %}
<h2>Login</h2>
<p>Please fill the form below.</p>
<form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" placeholder="Your email" value="{{ form.email.value|default:"" }}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label_tag }}
        <input type="password" class="form-control{% if form.password.errors %}is-invalid{% endif %}" id="id_password"
            name="password" value="{{ form.password.value|default:"" }}">
        {% if form.password.errors %}
        <div class="invalid-feedback">
            {{ form.password.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-xprimary">Submit</button>
</form>
{% endblock content %}

booktime/main/templates/signup.html
{% extends "base.html" %}
{% block content %}
<h2>Sign up</h2>
<p>Please fill the form below.</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" placeholder="Your email" value="{{ form.email.value|default:'' }}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password1.label_tag }}
        <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
            id="id_password1" name="password1" value="{{ form.password1.value|default:'' }}">
        {% if form.password1.errors %}
        <div class="invalid-feedback">
            {{ form.password1.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password2.label_tag }}
        <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}" id="id_password2"
            name="password2" value="{{ form.password2.value|default:'' }}">
        {% if form.password2.errors %}
        <div class="invalid-feedback">
            {{ form.password2.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    
</form>
{% endblock content %}